datasets:
  - dataset_id: pce_state_sapce4
    source: bea
    storage_dataset: pce_state
    bea_dataset: Regional
    bea_table_name: SAPCE4
    bea_frequency: A
    bea_start_year: 2000
    line_code: ALL
    geo_fips: STATE
    target_table: pce_state_annual
    enabled: true
  - dataset_id: state_regional_price_parities_sarpp
    source: bea
    storage_dataset: pce_state
    bea_dataset: Regional
    bea_table_name: SARPP
    bea_frequency: A
    bea_start_year: 2000
    line_code: ALL
    geo_fips: STATE
    target_table: pce_state_annual
    enabled: true
  - dataset_id: state_real_income_and_pce_sarpi
    source: bea
    storage_dataset: pce_state
    bea_dataset: Regional
    bea_table_name: SARPI
    bea_frequency: A
    bea_start_year: 2000
    line_code: ALL
    geo_fips: STATE
    target_table: pce_state_annual
    enabled: true
  - dataset_id: pce_state_sapce4_monthly
    source: bea
    storage_dataset: pce_state
    bea_dataset: Regional
    bea_table_name: SAPCE4
    bea_frequency: M
    bea_start_year: 2019
    line_code: ALL
    geo_fips: STATE
    target_table: pce_state_monthly
    enabled: false
  - dataset_id: census_state_population
    source: census
    storage_dataset: population_state
    census_dataset_path: acs/acs1
    census_variable: B01003_001E
    census_geography: state
    census_start_year: 2000
    census_frequency: A
    target_table: population_state_annual
    enabled: true
